#include "TranslationController.h"
#include "TranslationModelSession.h"
#include "translation/TranslationService.h"
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QJsonDocument>
#include <QDateTime>
#include <QDir>
#include <QStandardPaths>
#include <QtConcurrent>

namespace LAStudio {
TranslationController::TranslationController(ModelManager *models, RuntimeManager *runtimes, TranslationModelSession *session, QObject *parent) : QObject(parent), m_models(models), m_runtimes(runtimes), m_session(session) { m_autosave.setSingleShot(true); m_autosave.setInterval(750); connect(&m_autosave, &QTimer::timeout, this, &TranslationController::autosave); connect(&m_watcher, &QFutureWatcher<QVariantList>::finished, this, [this] { const bool cancelled = m_cancelToken && m_cancelToken->load(std::memory_order_relaxed); const QVariantList result = m_watcher.result(); m_processing = false; m_activeSegmentId.clear(); m_progress = 0; m_cancelToken.reset(); if (m_session) m_session->setProcessing(false); if (!cancelled && !result.isEmpty() && result.first().toMap().contains(QStringLiteral("error"))) setError(result.first().toMap().value(QStringLiteral("error")).toString()); else if (!cancelled) { applyPatches(result); addHistory(); } emit processingChanged(); }); loadHistory(); }
QString TranslationController::statusText() const { return m_processing ? QStringLiteral("Translating %1%").arg(m_progress) : (m_dirty ? QStringLiteral("Unsaved changes") : QStringLiteral("Ready")); }
void TranslationController::setSourceLanguage(const QString &value) { if (m_project.sourceLanguage == value) return; m_project.sourceLanguage = value; markDirty(); }
void TranslationController::setTargetLanguage(const QString &value) { if (m_project.targetLanguage == value) return; m_project.targetLanguage = value; markDirty(); }
void TranslationController::newProject() { if (m_processing) return; m_project = TranslationProject(); m_dirty = false; m_error.clear(); emit projectChanged(); emit errorTextChanged(); }
bool TranslationController::openProject(const QString &path) { if (m_processing) return false; TranslationProject project; QString error; if (!TranslationProject::load(path, project, &error)) { setError(error); return false; } m_project = std::move(project); m_dirty = false; emit projectChanged(); return true; }
bool TranslationController::importText(const QString &text) { if (m_processing) return false; QString error; if (!TranslationProject::importText(text, m_project, &error)) { setError(error); return false; } m_project.sourcePath.clear(); markDirty(); return true; }
bool TranslationController::importFile(const QString &path) { if (m_processing) return false; QFile file(path); if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) { setError(file.errorString()); return false; } const QString extension = QFileInfo(path).suffix().toLower(); QString error; const QString content = QString::fromUtf8(file.readAll()); const bool ok = extension == QStringLiteral("srt") || extension == QStringLiteral("vtt") ? TranslationProject::importSubtitle(content, extension, m_project, &error) : TranslationProject::importText(content, m_project, &error); if (!ok) { setError(error); return false; } m_project.sourcePath = QFileInfo(path).absoluteFilePath(); markDirty(); return true; }
bool TranslationController::saveProject() { QString error; if (!m_project.save(&error)) { setError(error); return false; } m_dirty = false; emit projectChanged(); return true; }
bool TranslationController::saveProjectAs(const QString &path) { if (path.isEmpty()) return false; m_project.projectPath = path; return saveProject(); }
bool TranslationController::exportResult(const QString &path) { if (path.isEmpty()) return false; QString error; const QString extension = QFileInfo(path).suffix().toLower(); QString output; if (extension == QStringLiteral("srt") || extension == QStringLiteral("vtt")) output = m_project.exportSubtitle(&error); else if (extension == QStringLiteral("json")) { QVariantMap root{{QStringLiteral("sourceLanguage"), m_project.sourceLanguage}, {QStringLiteral("targetLanguage"), m_project.targetLanguage}, {QStringLiteral("segments"), m_project.segments}}; output = QString::fromUtf8(QJsonDocument::fromVariant(root).toJson()); } else output = m_project.exportText(); if (!error.isEmpty()) { setError(error); return false; } QSaveFile file(path); if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) { setError(file.errorString()); return false; } file.write(output.toUtf8()); if (!file.commit()) { setError(file.errorString()); return false; } return true; }
void TranslationController::updateSegment(int index, const QVariantMap &patch) { if (index < 0 || index >= m_project.segments.size() || m_processing) return; QVariantMap segment = m_project.segments.at(index).toMap(); for (auto it = patch.cbegin(); it != patch.cend(); ++it) segment.insert(it.key(), it.value()); m_project.segments[index] = segment; markDirty(); }
void TranslationController::removeSegment(int index) { if (index < 0 || index >= m_project.segments.size() || m_processing) return; m_project.segments.removeAt(index); markDirty(); }
void TranslationController::addSegment() { if (m_processing) return; m_project.segments.append(QVariantMap{{QStringLiteral("id"), QStringLiteral("segment-%1").arg(m_project.segments.size() + 1)}, {QStringLiteral("sourceText"), QString()}, {QStringLiteral("targetText"), QString()}, {QStringLiteral("state"), QStringLiteral("ready")}}); markDirty(); }
void TranslationController::swapLanguages() { const QString source = m_project.sourceLanguage; m_project.sourceLanguage = m_project.targetLanguage; m_project.targetLanguage = source; markDirty(); }
void TranslationController::translateAll() { startTranslation(m_project.segments); }
void TranslationController::translateSegment(int index) { if (index >= 0 && index < m_project.segments.size()) { const QVariantMap segment = m_project.segments.at(index).toMap(); startTranslation({segment}, segment.value(QStringLiteral("id")).toString()); } }
void TranslationController::cancel() { if (!m_processing) return; if (m_cancelToken) m_cancelToken->store(true, std::memory_order_relaxed); m_watcher.cancel(); }
bool TranslationController::loadHistoryItem(const QString &id) { if (id.isEmpty() || m_processing) return false; for (const QVariant &historyValue : std::as_const(m_history)) { const QVariantMap item = historyValue.toMap(); if (item.value(QStringLiteral("id")).toString() != id) continue; TranslationProject project; project.sourceLanguage = item.value(QStringLiteral("sourceLanguage"), QStringLiteral("en")).toString(); project.targetLanguage = item.value(QStringLiteral("targetLanguage"), QStringLiteral("vi")).toString(); project.sourceFormat = item.value(QStringLiteral("sourceFormat"), QStringLiteral("text")).toString(); project.segments = item.value(QStringLiteral("segments")).toList(); if (project.segments.isEmpty()) return false; m_project = std::move(project); m_dirty = true; m_error.clear(); emit projectChanged(); emit errorTextChanged(); return true; } return false; }
bool TranslationController::deleteHistoryItem(const QString &id) { if (id.isEmpty()) return false; for (int index = 0; index < m_history.size(); ++index) { if (m_history.at(index).toMap().value(QStringLiteral("id")).toString() != id) continue; QVariantList updatedHistory = m_history; updatedHistory.removeAt(index); QSaveFile file(historyPath()); if (!file.open(QIODevice::WriteOnly)) return false; file.write(QJsonDocument::fromVariant(updatedHistory).toJson()); if (!file.commit()) return false; m_history = std::move(updatedHistory); emit historyChanged(); return true; } return false; }
void TranslationController::clearHistory() { m_history.clear(); QFile::remove(historyPath()); emit historyChanged(); }
void TranslationController::markDirty() { m_dirty = true; m_error.clear(); if (!m_project.projectPath.isEmpty()) m_autosave.start(); emit projectChanged(); emit errorTextChanged(); }
void TranslationController::setError(const QString &message) { m_error = message; if (m_session) m_session->setError(message); emit errorTextChanged(); }
void TranslationController::startTranslation(const QVariantList &segments, const QString &activeSegmentId) { if (m_processing) { setError(QStringLiteral("A translation request is already running.")); return; } if (!m_session || !m_session->activeConfiguration()) { setError(QStringLiteral("Select and load a Translation model and runtime first.")); return; } TranslationRequest request; QString error; if (!TranslationService::prepareConfiguration(*m_session->activeConfiguration(), m_project.sourceLanguage, m_project.targetLanguage, request, &error)) { setError(error); return; } m_cancelToken = std::make_shared<std::atomic_bool>(false); request.cancelToken = m_cancelToken; m_error.clear(); m_processing = true; m_activeSegmentId = activeSegmentId; m_progress = 0; m_session->clearError(); m_session->setProcessing(true); emit errorTextChanged(); emit processingChanged(); m_watcher.setFuture(QtConcurrent::run([request, segments] { QVariantList patches; QString error; if (!TranslationService::translate(request, segments, patches, &error)) return QVariantList{QVariantMap{{QStringLiteral("error"), error}}}; return patches; })); }
void TranslationController::applyPatches(const QVariantList &patches) { for (const QVariant &patchValue : patches) { const QVariantMap patch = patchValue.toMap(); const QString id = patch.value(QStringLiteral("id")).toString(); for (int i = 0; i < m_project.segments.size(); ++i) { QVariantMap segment = m_project.segments.at(i).toMap(); if (segment.value(QStringLiteral("id")).toString() != id) continue; for (auto it = patch.cbegin(); it != patch.cend(); ++it) segment.insert(it.key(), it.value()); m_project.segments[i] = segment; break; } } markDirty(); }
void TranslationController::autosave() { if (m_dirty && !m_project.projectPath.isEmpty()) saveProject(); }
QString TranslationController::historyPath() const { const QString base = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + QStringLiteral("/history"); QDir().mkpath(base); return base + QStringLiteral("/translation_history.json"); }
void TranslationController::loadHistory() { QFile file(historyPath()); if (!file.open(QIODevice::ReadOnly)) return; const QJsonDocument document = QJsonDocument::fromJson(file.readAll()); if (document.isArray()) m_history = document.array().toVariantList(); emit historyChanged(); }
void TranslationController::addHistory() { if (m_project.segments.isEmpty()) return; const QVariantMap first = m_project.segments.first().toMap(); const QVariantMap last = m_project.segments.last().toMap(); QVariantMap item{{QStringLiteral("id"), QString::number(QDateTime::currentMSecsSinceEpoch())}, {QStringLiteral("timestamp"), QDateTime::currentDateTime().toString(QStringLiteral("yyyy-MM-dd hh:mm:ss"))}, {QStringLiteral("sourceLanguage"), m_project.sourceLanguage}, {QStringLiteral("targetLanguage"), m_project.targetLanguage}, {QStringLiteral("sourceFormat"), m_project.sourceFormat}, {QStringLiteral("sourcePreview"), first.value(QStringLiteral("sourceText")).toString()}, {QStringLiteral("targetPreview"), last.value(QStringLiteral("targetText")).toString()}, {QStringLiteral("segments"), m_project.segments}}; m_history.prepend(item); while (m_history.size() > 30) m_history.removeLast(); QSaveFile file(historyPath()); if (file.open(QIODevice::WriteOnly)) { file.write(QJsonDocument::fromVariant(m_history).toJson()); file.commit(); } emit historyChanged(); }
} // namespace LAStudio
